<?php
/*
 * LiteMage plugin for LiteSpeed web server
 * @copyright  Copyright (c) 2015 LiteSpeed Technologies, Inc. (http://www.litespeedtech.com)
 */

/* This is a private block (place holder template) to correct any variable that was set in public cached javascript earlier.
 * So you do not need to modify your existing code in third-part's theme/template/extension.
 * Since this will be in private block, so all the information can be set correctly for a particular user based on his own session information
 *
 * Example:
 * in head script from a sns theme, there is
 * var isLoggedIn="<?php echo (Mage::getSingleton('customer/session')->isLoggedIn())?1:0?>";
 *
 * isLoggedIn is set to 1 or 0, and is in public cache
 * Here we just reassign it to its correct value.
 *
 * You can use this template add all other javascript global variables that require different value for individual user.
 * logged_in and logged_out events will be added automatically to purge this block.
 * If you have other variables that require different purge events, please modify litemage config.xml to include those events.
 *
 * Since this file will be overridden when you upgrade litemage, please keep your own copy if you make any modification.
 */

?>

<?php if ($this->isAllowed()):?>
<script type="text/javascript">
//<![CDATA[
    isLoggedIn="<?php echo (Mage::getSingleton('customer/session')->isLoggedIn())?1:0?>";
//]]>
</script>
<?php endif?>